### ISSUE TITLE
Responsivo no Sobre

### ISSUE THREAD

**Issue by marcusboyds** [BenitoPedro13/Dutra.design#34]
# Fazer o sobre nesse layout apresentado e aplicar efeito parallax
![image](https://user-images.githubusercontent.com/73398891/119263633-44f0b600-bbb6-11eb-984a-f4b3d8282cb9.png)

# Efeito Parallax
## 1. Usuário scrolla pra baixo
![image](https://user-images.githubusercontent.com/73398891/119263695-82554380-bbb6-11eb-997f-fb34bdbac0d5.png)
## 2. A foto scrolla pra cima proporcionalmente
![image](https://user-images.githubusercontent.com/73398891/119263845-17f0d300-bbb7-11eb-8434-e9d91c8baa8b.png)

### OBS. Seria interessante o scroll ter inercia e mesmo que pare o usuario de scrollar a foto continua deslizando pra cima, como se tivesse uma manteiga embaixo dela e uma vez que tu empurro, nunca mais parada de deslizar pra cima!!!

**Comment by BenitoPedro13** [comment]
.
